-- CONNECTION: url=jdbc:db2://db2w-bdctcim.eu-de.db2w.cloud.ibm.com:50001/BLUDB:sslConnection=true;
-- New script: Smukfest - DEVELOPMENT - watch_dev_backend
-- Date: 	   14 May 2024
-- Time: 	   14.16.19
-- User:	   sravn
-- Workspace:  /Users/sravn/Library/DBeaverData/workspace6

---------------------------------------------------------------------

-- dataintegration users for DEVELOPMENT

SET SCHEMA DEVELOPMENT;

DROP ROLE ROLE_DATA_INTEGRATION_DEV;
CREATE ROLE ROLE_DATA_INTEGRATION_DEV;

GRANT ROLE ROLE_DATA_INTEGRATION_DEV TO USER DATA_INTEGRATION_DEV;

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE SALESDATA_ALL TO ROLE ROLE_DATA_INTEGRATION_DEV;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE MILLSDATA_ALL TO ROLE ROLE_DATA_INTEGRATION_DEV;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE USAGE_LOG TO ROLE ROLE_DATA_INTEGRATION_DEV;



-- dataintegration users for TEST

SET SCHEMA TEST;

DROP ROLE ROLE_DATA_INTEGRATION_TEST;
CREATE ROLE ROLE_DATA_INTEGRATION_TEST;

GRANT ROLE ROLE_DATA_INTEGRATION_TEST TO USER SMUK_INTEGRATION_TEST;

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE SALESDATA_ALL TO ROLE ROLE_DATA_INTEGRATION_TEST;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE MILLSDATA_ALL TO ROLE ROLE_DATA_INTEGRATION_TEST;



-- dataintegration users for PRODUCTION

SET SCHEMA PRODUCTION;

DROP ROLE ROLE_DATA_INTEGRATION_PROD;
CREATE ROLE ROLE_DATA_INTEGRATION_PROD;

GRANT ROLE ROLE_DATA_INTEGRATION_PROD TO USER SMUK_INTEGRATION_PROD;

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE SALESDATA_ALL TO ROLE ROLE_DATA_INTEGRATION_PROD;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE MILLSDATA_ALL TO ROLE ROLE_DATA_INTEGRATION_PROD;



